version: 2

sources:
  - name: raw-trip-data
    database: de-zoomcamp-376020 # dataset in bigquery
    schema: week_4_dbt

    tables:
      - name: yellow_taxi_data
      - name: green_taxi_data
# models:
#   - name: stage_green_trip_data # should this name correspond to the table/view name?
