version: '3.1'

services:
  prefect-dashboard:
    image: de_pipeline/week_2:latest
    build:
      context: ./application
      dockerfile: ./Dockerfile
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
    volumes:
      - ./prefect_volume:/root/.prefect
    ports:
      - 4200:4200
    command: [ "poetry", "run", "prefect", "orion", "start" ]
